# frozen_string_literal: true

# 2.14-D — Falcon-side gRPC server for the ghz cross-server bench.
#
# Boots `Async::HTTP::Server` (the same wire engine Falcon uses) with
# `Async::GRPC::Dispatcher` routing requests to an EchoStream service that
# matches `bench/grpc_stream.proto`. The bench harness drives this server
# and `bench/grpc_stream.ru` (Hyperion side) with the same ghz config so
# the comparison is apples-to-apples on the wire (h2 over TLS), with the
# only structural difference being the dispatcher (Hyperion = Rack 3 +
# trailers, Falcon = async-grpc).
#
# Usage:
#   bundle exec ruby bench/grpc_stream_falcon.rb [port [stream_count [payload_bytes]]]
#
# Defaults match the Hyperion-side rackup: port 19292, 100 messages per
# server-stream, 10 bytes per message.
#
# `Protocol::GRPC::Interface` is the async-grpc-native interface shape;
# the `marshal:` / `unmarshal:` knobs let us bypass Google's protobuf
# code-gen (we already have `echo_pb.rb` from `grpc_tools_ruby_protoc`,
# but treating the EchoReply payload as opaque bytes keeps the Falcon
# server identical-shape to the Hyperion-side hand-rolled rackup —
# fixed payload, no per-request encoding cost).
$LOAD_PATH.unshift(__dir__) # echo_pb.rb / echo_services_pb.rb live next to this file when present
$LOAD_PATH.unshift('/tmp/falcon-grpc') # bench host: bundle setup happens in /tmp/falcon-grpc

require 'async'
require 'async/grpc'
require 'async/grpc/service'
require 'async/grpc/dispatcher'
require 'async/http/server'
require 'async/http/endpoint'
require 'protocol/grpc/interface'
require 'echo_pb' # generated by grpc_tools_ruby_protoc; lives in /tmp/falcon-grpc

PORT          = Integer(ARGV[0] || ENV['PORT'] || 19_292)
STREAM_COUNT  = Integer(ARGV[1] || ENV['GRPC_STREAM_COUNT']  || 100)
PAYLOAD_BYTES = Integer(ARGV[2] || ENV['GRPC_PAYLOAD_BYTES'] || 10)
TLS_DIR       = ENV.fetch('TLS_DIR', '/tmp/hyperion-grpc-bench')

# Reuse the same EchoRequest / EchoReply proto messages that
# grpc_tools_ruby_protoc emitted from `echo.proto`.
class EchoStreamInterface < Protocol::GRPC::Interface
  rpc :ServerStream,
      request_class: Hyperion::Bench::EchoRequest,
      response_class: Hyperion::Bench::EchoReply
  rpc :Unary,
      request_class: Hyperion::Bench::EchoRequest,
      response_class: Hyperion::Bench::EchoReply
end

# Pre-build the response message once. async-grpc encodes it on each
# `output.write`, so we still pay the protobuf encode per message —
# matching the per-message accounting on the Hyperion side, where the
# rackup precomputes the wire frame but every grpc-write path on a real
# Rails app would also re-encode.
PAYLOAD_STR = ('x' * PAYLOAD_BYTES).b.freeze
REPLY       = Hyperion::Bench::EchoReply.new(payload: PAYLOAD_STR).freeze

class EchoStreamService < Async::GRPC::Service
  def server_stream(input, output, _call)
    input.read # drain the request
    STREAM_COUNT.times { output.write(REPLY) }
  end

  def unary(input, output, _call)
    input.read
    output.write(REPLY)
  end
end

# `--insecure` on ghz expects plaintext h2 (h2c), but `Async::HTTP`
# autoselects the transport from the URL scheme. We use `https://` +
# self-signed cert so ghz can drive it with `--skipTLS`, identical to
# the Hyperion-side configuration. If TLS files are missing we fall
# back to plaintext (`http://`) — the harness regenerates the cert at
# `$TLS_DIR/cert.pem` before launching either server.
endpoint_url = if File.exist?("#{TLS_DIR}/cert.pem")
                 "https://127.0.0.1:#{PORT}"
               else
                 "http://127.0.0.1:#{PORT}"
               end
ssl_context = if endpoint_url.start_with?('https://')
                ctx = OpenSSL::SSL::SSLContext.new
                ctx.cert = OpenSSL::X509::Certificate.new(File.read("#{TLS_DIR}/cert.pem"))
                ctx.key  = OpenSSL::PKey::RSA.new(File.read("#{TLS_DIR}/key.pem"))
                ctx.alpn_select_cb = ->(protocols) { protocols.include?('h2') ? 'h2' : protocols.first }
                ctx.alpn_protocols = %w[h2 http/1.1]
                ctx
              end

endpoint = Async::HTTP::Endpoint.parse(endpoint_url, ssl_context: ssl_context)
dispatcher = Async::GRPC::Dispatcher.new
dispatcher.register(EchoStreamService.new(EchoStreamInterface, 'hyperion.bench.EchoStream'))
server = Async::HTTP::Server.new(dispatcher, endpoint)

warn(
  '[falcon-grpc] up: ' \
  "url=#{endpoint_url} stream_count=#{STREAM_COUNT} payload_bytes=#{PAYLOAD_BYTES}"
)

Async do
  server.run
end
